sonar.organization=jamesmittlerii
sonar.projectKey=jamesmittlerii_obdii
sonar.host.url=https://sonarcloud.io

sonar.sources=flutter_obdii/lib,kotlin_obdii/app/src/main,kotlin_obdii/androidApp/src/main,kotlin_obdii/obdlib/src/main
sonar.tests=flutter_obdii/test,kotlin_obdii/app/src/test,kotlin_obdii/androidApp/src/androidTest

sonar.dart.lcov.reportPaths=flutter_obdii/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=kotlin_obdii/app/build/reports/jacoco/test/jacocoTestReport.xml
